export const allDropdown = document.querySelectorAll('#sidebar .side-dropdown');
export const sidebar = document.getElementById('sidebar');
export const toggleSidebar = document.querySelector('nav .toggle-sidebar');
export const allSideDivider = document.querySelectorAll('#sidebar .divider');
export const profile = document.querySelector('nav .profile');
export const imgProfile = profile.querySelector('img');
export const dropdownProfile = profile.querySelector('.profile-link');
export const allMenu = document.querySelectorAll('main .content-data .head .menu');
export const allProgress = document.querySelectorAll('main .card .progress');

export const $sellsBtn = document.querySelector(".ventaBtn")
export const $pageTitle = document.querySelector(".page-title")
export const $rootValue = document.querySelector(".root-value")
export const $rootSection = document.querySelector(".root-section")
export const serviceButtons = document.querySelectorAll("main .info-data .option-btn");
export const $dataContainer = document.querySelector(".content-data");
export const $dataTitle = document.querySelector(".data .content-data .head h3");
export const $infoData = document.querySelector(".data .info-data");
export const $filtersButton = document.querySelector("filter-button") ;
export const $filterMenu = document.querySelector(".filters-box");
export const $titleDiv = document.querySelector(".content-data .head");